import { Providers } from "@/components/Providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">
        <Providers>
          <div className="mx-auto max-w-3xl p-6">
            <header className="mb-6 flex items-center justify-between">
              <h1 className="text-2xl font-semibold">Doc Q&A (RAG)</h1>
              <nav className="flex gap-4 text-sm">
                <a className="underline" href="/">Home</a>
                <a className="underline" href="/upload">Upload</a>
                <a className="underline" href="/ask">Ask</a>
              </nav>
            </header>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
